version: '3.8'

services:
  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ['./entrypoint.sh']
    restart: on-failure:10
    ports:
      - 8086:8086
    networks:
      - iot

  telegraf:
    image: telegraf:1.26
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
      # - mosquitto
    ports:
      - 8125:8125
    networks:
      - iot

  grafana:
    image: grafana/grafana-oss:8.4.3
    container_name: grafana-server
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    networks:
      - iot

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1881:1881
    networks:
      - iot

networks:
  iot:
volumes:
  grafana-storage:
  influxdb-storage:
